version: "3"

services:
  mysql:
    image: "mysql/mysql-server"
    restart: 'no'
    ports:
      - '3306:3306'
    volumes: 
      - ./persist/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
networks: 
  default: 
    name: phpdev
